### ISSUE TITLE
Things to fix and beware of

### ISSUE THREAD

**Issue by mountaingoat69** [WebCab-Design/women.peaksrecovery.com#1]
@TheBurnsby 
Would like to make admissions section part of main menu. Main menu should read: Home - Recovery Program - Admissions - Contact... Do the same for men's page! 

I updated all verbiage for Treatment Philosophy pages and Contact page. Those changes are not reflecting in localhost view. Maybe wrong links or something? I don't know, not the developer haha. 

I have not updated Mental Health and Addiction Treatment pages. Maybe same link issues persist with these pages as well. Just FYI.

**Comment by xeaone** [comment]
- Moved Admissions to the menu
- I am thinking you will need to empty your dist directory then muleify/'npm run serve' it again.
- Fixed the links on all pages including Mental Health and Addiction Treatment pages.
